CREATE DATABASE EJEMPLOS 
GO
USE EJEMPLOS 

CREATE TABLE EMPLEADOS(
    LEGAJO BIGINT NOT NULL,
    IDSUCURSAL INT NOT NULL,
    APELLIDO VARCHAR(30) NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL
)

ALTER TABLE EMPLEADOS
ADD DNI VARCHAR(10) NOT NULL
GO 

ALTER TABLE EMPLEADOS 
ADD CONSTRAINT PK_EMPLEADOS PRIMARY KEY(LEGAJO, IDSUCURSAL)

ALTER TABLE EMPLEADOS 
ADD CONSTRAINT DNI_UNICO UNIQUE (DNI)

ALTER TABLE EMPLEADOS 
ADD CONSTRAINT FK_SUCURSAL FOREIGN KEY (IDSUCURSAL) REFERENCES SUCURSALES (IDSUCURSAL)



ALTER TABLE EMPLEADOS 
ADD AUX CHAR NULL

ALTER TABLE EMPLEADOS 
ALTER COLUMN AUX DATE NOT NULL

ALTER TABLE EMPLEADOS 
DROP COLUMN AUX

create table ciudades (
    IDCIUDAD INT NOT NULL PRIMARY KEY,
    CIUDAD VARCHAR(50) NOT NULL,
    IDPROVINCIA INT NOT NULL
)
GO

CREATE TABLE SUCURSALES(
    IDSUCURSAL INT NOT NULL,
    DIRECCION VARCHAR(50) NOT NULL,
    TELEFONO VARCHAR(15) NULL,
    MAIL VARCHAR(15) NULL,
    IDCIUDAD INT NOT NULL FOREIGN KEY REFERENCES CIUDADES (IDCIUDAD),
    PRIMARY KEY (IDSUCURSAL)
)
GO

DROP TABLE SUCURSALES

CREATE TABLE JUSTIFICACIONES(
    IDJUSTIFICACION INT NOT NULL,
    JUSTIFICACION VARCHAR(100) NOT NULL,
    PRIMARY KEY (IDJUSTIFICACION)
)
GO

CREATE TABLE INASISTENCIAS(
    LEGAJO BIGINT NOT NULL,
    IDSUCURSAL INT NOT NULL,
    FECHA SMALLDATETIME NOT NULL DEFAULT (GETDATE()),
    IDJUSTIFIACION INT NULL FOREIGN KEY REFERENCES JUSTIFICACIONES (IDJUSTIFICACION),
    PRIMARY KEY (LEGAJO, IDSUCURSAL, FECHA)
)

ALTER TABLE INASISTENCIAS
ADD CONSTRAINT FK_INASISTENCIAS_EMPLEADO FOREIGN KEY (LEGAJO, IDSUCURSAL)
REFERENCES EMPLEADOS (LEGAJO, IDSUCURSAL)

INSERT INTO JUSTIFICACIONES VALUES (1, 'VACACIONES')
INSERT INTO JUSTIFICACIONES VALUES (2, 'ENFERMEDAD')

ALTER TABLE CIUDADES 
ADD CONSTRAINT CHK_IDPROVINCIA CHECK (IDPROVINCIA>=0 AND IDPROVINCIA <=24)



CREATE TABLE CARRERAS(
    ID VARCHAR(4) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    FECHACREACION SMALLDATETIME CHECK(FECHACREACION<GETDATE()) NOT NULL,
    MAIL VARCHAR(100) NOT NULL,
    NIVEL VARCHAR(12) CHECK (NIVEL='Diplomatura' or NIVEL='Pregrado' or NIVEL='Grado' or NIVEL='Posgrado')
)


CREATE TABLE MATERIAS(
    ID INT IDENTITY (1,1),
    IDCARRERA VARCHAR(4) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    CARGAHORARIA SMALLINT CHECK(CARGAHORARIA>0) NOT NULL,
    PRIMARY KEY (ID)
)

ALTER TABLE MATERIAS
ADD CONSTRAINT FK_IDCARRERA FOREIGN KEY (IDCARRERA) REFERENCES CARRERAS (ID)

CREATE TABLE ALUMNOS(
    ID INT IDENTITY(1000,1) PRIMARY KEY,
    IDCARRERA VARCHAR(4) NOT NULL FOREIGN KEY REFERENCES CARRERAS (ID),
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50) NOT NULL,
    FECHANACIMIENTO SMALLDATETIME CHECK(FECHANACIMIENTO<GETDATE()),
    MAIL VARCHAR(100) NOT NULL UNIQUE,
    TELEFONO VARCHAR(30)
)

